const goats = [
  {
    id: 'goat1',
    name: 'billy',
    disposition: 'rude',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Hausziege_04.jpg',
    fullness: '67',
    favPose: 'downward facing dog',
    isFainting: true,
    color: 'brown',
  },
  {
    id: 'goat2',
    name: 'sally',
    disposition: 'tired',
    imageUrl: 'https://pbs.twimg.com/profile_images/980547001166295041/eBs20xF4.jpg',
    fullness: '22',
    favPose: 'corpse',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat3',
    name: 'martin',
    disposition: 'happy',
    imageUrl: 'https://i.cbc.ca/1.4930973.1543875171!/fileImage/httpImage/image.jpg_gen/derivatives/16x9_780/goats.jpg',
    fullness: '85',
    favPose: 'warror I',
    isFainting: false,
    color: 'gray',
  },
  {
    id: 'goat4',
    name: 'beatrice',
    disposition: 'snobbish',
    imageUrl: 'https://i.imgur.com/EX1wOKs.jpg',
    fullness: '35',
    favPose: 'tree',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat5',
    name: 'angie',
    disposition: 'loud',
    imageUrl: 'https://www.psephizo.com/wp-content/uploads/2018/09/1438297793139.jpeg',
    fullness: '14',
    favPose: 'pigeon',
    isFainting: false,
    color: 'brown',
  },
];

export default goats;
